3DVar
ComputationalScienceLaboratory/DATools pull request #17
Opened 2022-07-11 16:34 UTC by AndreyAPopov

2022-07-12 01:45 UTC, amitns122 requested changes

2022-07-12 01:45 UTC, amitns122 commented on src/+datools/+variational/ThreeDVar.m
> +                'HessianApproximation', {'lbfgs', 50});
We can specify Hessian vector products. Look at HessianMultiplyFcn option for fmincon.

2022-07-12 01:45 UTC, amitns122 commented on src/+datools/+variational/ThreeDVar.m
> +                'HessianApproximation', {'lbfgs', 50});
define hess = @(Hinfo, v) hessfunc(Hinfo, v, ........ stuff to compute the HVP)

2022-07-12 01:45 UTC, amitns122 commented on src/+datools/+variational/ThreeDVar.m
> +                'HessianApproximation', {'lbfgs', 50});
options = optimoptions('fmincon', 'SpecifyObjectiveGradient', true, 'CheckGradients', false, ...
    'Algorithm', 'trust-region-reflective', 'HessianMultiplyFcn', hess, 'Display', 'off');

2022-07-12 01:45 UTC, amitns122 commented on src/+datools/+variational/ThreeDVar.m
> +            function [c, g] = cost(x, xb, dB, y, dR, H, Hadjoint)
function [c, g, Hinfo] = ...

2022-07-12 01:45 UTC, amitns122 commented on src/+datools/+variational/ThreeDVar.m
> +            end
Hinfo = [ ]. 
Can return stuff but matlab does not allow a direct hvp output, because its weird.

2022-07-12 01:45 UTC, amitns122 commented on src/+datools/+variational/ThreeDVar.m
> +            end
function hv =hessfunc(hinfo, v, dB, H, dR)
hv = dB\v + H.'*(dR\(H*v));
end

Just use the linearization and stuff as well.

2022-07-12 17:57 UTC, AndreyAPopov commented
The reason why I don't want to add Hessian information is because with Hesian vector products the method would have to use a linear solver. For large systems this could be significantly more expensive than using LBFGS. I vote we simply use LBFGS and be done with it.

2023-04-12 15:41 UTC, AndreyAPopov commented
I don't have a copy of matlab with the optimization toolbox installed, so can you finish this if possible? I don't want to leave us without even a simple 3DVar

2023-04-12 15:43 UTC, amitns122 commented
Alright. I'll download this version and finish working on it.

2023-04-14 16:28 UTC, amitns122 commented
@AndreyAPopov Okay. I think 3DVar is done.

2023-04-14 17:56 UTC, AndreyAPopov commented on src/+datools/+variational/ThreeDVar.m
> +                hessv = @(Hax, v) dB\v + Hax*(dR\(Hax.'*v));
I think technically this needs to be Hax' not Hax.', as we want the adjoint not the transpose.

2023-04-14 17:57 UTC, AndreyAPopov commented on src/+datools/+variational/ThreeDVar.m
>              Hadjoint = @(x) obs.linearization(t, x).';
Ha, I make the same mistake here. I am so used to typing .'

2023-04-14 19:19 UTC, amitns122 commented on src/+datools/+variational/ThreeDVar.m
> +                    'HessianApproximation', {'lbfgs', 30});
Changed to 50.  We can make it a parameter when DATools 2.0 is done.

2023-04-14 19:34 UTC, merged